# -*- coding: utf-8 -*-
"""aspect_level_summarisation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4yJpysEPiNINBU6Sp0zRjGEO-z9bzkc
"""

import pandas as pd

df=pd.read_csv("/content/readability1.csv")
reviews=df["Review "]
colleges=df["College "]
reviews

!pip install transformers
college_name=input("Enter college name:")
from transformers import pipeline
def summarize(text):
  summarizer = pipeline("summarization", model="stevhliu/my_awesome_billsum_model")
  #a= summarizer(text,max_length=50)
  a= summarizer(text,max_length=100)
  return a[0]['summary_text']

def aspect_text(d,text):
  arr=text.split("\n")
  for aspect in arr:
    a=aspect.split(":")
    if a[0] not in d.keys():
      #if (a[1]):
      if len(a)>1:
        d[a[0]]=a[1]
    else:
        v=d[a[0]]
        d[a[0]]=v+a[1]
        
  return d

d=dict()
for text,col in zip(reviews,colleges):
  
  if col==college_name:
    summary=""
    d=aspect_text(d,text)
    print(d)
    #j=d.copy()
    for x,y in list(d.items()):
      summarised_text=summarize(x)
      print(summarised_text)
      a="".join(summarised_text)
      summary= summary+ a
      print(summary)
      if col in d.keys():
        val=d[col]
        d[col]=val+summary
      else:
        d[col]=summary
  print(len(d["Remarks "]))
  print(d.keys())

print(d.keys())
for i,j in list(d.items()):
  if i==college_name:
    del d[i]
  
# df1=pd.DataFrame(d,index=[0])
# df1.to_csv('/content/summary.csv')

final_summary=dict()
for aspect,sum_text in d.items():
  summary=summarize(sum_text)
  final_summary[aspect]=summary
print(final_summary)